sudo: required
dist: trusty

env:
  - APP_SETTINGS=config.TestingConfig DATABASE_URL=postgresql://localhost/pitchup_test

language: python
python:
   - "3.5.1"

script:
 - npm test

addons:
  postgresql: "9.3"

install:
  - pip install coveralls
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database pitchup_test;' -U postgres
  - python manage.py db init
  - python manage.py db migrate
  - python manage.py db upgrade
  - sudo apt-get update -q
  - sudo wget -qO- https://deb.nodesource.com/setup_5.x | sudo bash -
  - sudo apt-get install -y nodejs postfix
  - nodejs -v
  - sudo npm install -g grunt-cli
  - sudo npm install
  - ./node_modules/bower/bin/bower install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm start &
  - sleep 5

after_success:
  - coveralls
